sudo: false

language: scala

jdk:
  - openjdk8

scala:
  - 2.12.10

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt

env:
  - LOG_LEVEL=ERROR

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
